### ISSUE TITLE
websocket  closed 1006

### ISSUE THREAD

**Issue by ProgrammerCreator** [abi/screenshot-to-code#46] opened 2023-11-20 07:16 UTC
![1700464540408](https://github.com/abi/screenshot-to-code/assets/38424449/0091eb42-4b2b-4d20-8969-af1eb649df1e)
![1700464582272](https://github.com/abi/screenshot-to-code/assets/38424449/43aea2a7-2fd8-4db8-bd1f-277a306ed9bc)

**Comment by diepdo1810** [comment] 2023-11-20 10:25
Same. How to fix?

**Comment by samya123456** [comment] 2023-11-20 13:06
may be the port number for the backend is not correct. it should be 7001. change to 7001 and try.

**Comment by Alexandersheptulya** [comment] 2023-11-20 14:22
No. It's really bug of code. In my local docker i'm getting it too. Mb problems with timeouts?
Backend unexpected close connection

**Comment by codingsf** [comment] 2023-11-20 16:56
so do i. i just start with docker file. same error happened!

**Comment by Jonathan-Adly** [comment] 2023-11-20 18:09
Port 7000 and docker on some Macs doesn't work. Make sure you are running the latest code, with port 7001.

**Comment by abi** [comment] 2023-11-20 18:20
Port number should be updated everywhere in the code to 7001. If you have an issue, please pull from latest and try again. If it still doesn't work, let us know.

**Comment by chamakov** [comment] 2023-11-20 18:53
Same issue on the online version... any fix or workaround?

**Comment by abi** [comment] 2023-11-20 19:01
Please look at your backend logs. Hosted version is just a demo and not debugging it right now.

**Comment by KellHuang** [comment] 2023-11-21 00:55
Hello,I'm encountering an issue with my FastAPI/Starlette application involving WebSockets. The application is throwing a WebSocketDisconnect: CloseCode.ABNORMAL_CLOSURE error under certain conditions.

Error Message:
Exception in ASGI application
Traceback (most recent call last):
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 247, in run_asgi
result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in call
return await self.app(scope, receive, send)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\fastapi\applications.py", line 276, in call
await super().call(scope, receive, send)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\starlette\applications.py", line 122, in call
await self.middleware_stack(scope, receive, send)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\starlette\middleware\errors.py", line 149, in call
await self.app(scope, receive, send)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\starlette\middleware\cors.py", line 75, in call
await self.app(scope, receive, send)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\starlette\middleware\exceptions.py", line 79, in call
raise exc
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\starlette\middleware\exceptions.py", line 68, in call
await self.app(scope, receive, sender)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in call
raise e
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in call
await self.app(scope, receive, send)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\starlette\routing.py", line 718, in call
await route.handle(scope, receive, send)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\starlette\routing.py", line 341, in handle
await self.app(scope, receive, send)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\starlette\routing.py", line 82, in app
await func(session)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\fastapi\routing.py", line 289, in app
await dependant.call(**values)
File "I:\screenshot-to-code\backend\backend\main.py", line 65, in stream_code_test
params = await websocket.receive_json()
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\starlette\websockets.py", line 133, in receive_json
self._raise_on_disconnect(message)
File "C:\Users\wenyu\AppData\Local\pypoetry\Cache\virtualenvs\backend-Pn3rOF5f-py3.10\lib\site-packages\starlette\websockets.py", line 105, in _raise_on_disconnect
raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: CloseCode.ABNORMAL_CLOSURE

I would appreciate any insights or suggestions on what might be causing this issue and how to resolve it. Thank you in advance for your help!


![333](https://github.com/abi/screenshot-to-code/assets/118271893/d4d99c96-35f1-4a10-91a7-f8cbaafa508c)

**Comment by abi** [comment] 2023-11-21 02:29
That is really strange. @KellHuang does this happen all the time?

**Comment by ProgrammerCreator** [comment] 2023-11-21 03:29
I pulled the latest code and changed the new port globally, but it still can't connect.

**Comment by codingsf** [comment] 2023-11-21 07:06
i solved the problem!  the reason caused by that docker env not read .env file('VITE_WS_BACKEND_URL=ws://127.0.0.1:7001'). you can modify code '
export const WS_BACKEND_URL =
--
6 | import.meta.env.VITE_WS_BACKEND_URL \|\| "ws://127.0.0.1:7001";
' in path '/frontend/src/config.ts', replace '127.0.0.1' to your outer ip(192.168.1.xx)

**Comment by diepdo1810** [comment] 2023-11-21 07:23
> Port 7000 and docker on some Macs doesn't work. Make sure you are running the latest code, with port 7001.

Thanks. I fixed it.

**Comment by nzd520** [comment] 2023-11-21 13:17
> 我解决了问题！docker env 未读取 .env 文件（'VITE_WS_BACKEND_URL=ws://127.0.0.1:7001'）引起的原因。您可以修改代码' export const WS_BACKEND_URL = import.meta.env.VITE_WS_BACKEND_URL || “ws://127.0.0.1:7001”; ' 在路径 '/frontend/src/config.ts' 中，将 '127.0.0.1' 替换为您的外部 IP(192.168.1.xx)

it cant work

**Comment by abi** [comment] 2023-11-21 16:48
Can you try updating /127.0.0.1 to your local IP? Or to localhost? That might fix some of these issues.

**Comment by ProgrammerCreator** [comment] 2023-11-22 01:19
> > 我解决了问题！docker env 未读取 .env 文件（'VITE_WS_BACKEND_URL=ws：//127.0.0.1：7001'）引起的原因。您可以修改代码' export const WS_BACKEND_URL = import.meta.env.VITE_WS_BACKEND_URL ||“ws://127.0.0.1:7001”;' 在路径 '/frontend/src/config.ts' 中，将 '127.0.0.1' 替换为您的外部 IP（192.168.1.xx）
> 
> 它行不通

I've tried this method, but it still doesn't work, it's just a little faster to respond to errors

**Comment by illiyyin** [comment] 2023-11-22 04:21
is this because the python version?

**Comment by wudiyingying** [comment] 2023-11-22 06:32
i tried in your website "https://picoapps.xyz/free-tools/screenshot-to-code" ,same error happens!
<img width="845" alt="image" src="https://github.com/abi/screenshot-to-code/assets/95748115/c2201934-e3bf-4933-9a50-0672005257a2">

**Comment by linxp001** [comment] 2023-11-22 14:32
新建frontend/.env.local，在里面配置正确的URL：VITE_WS_BACKEND_URL=ws://192.168.1.xx:7001

然后把镜像删除重新创建

**Comment by ash-r1** [comment] 2023-11-22 14:49
In my case, I had to increase Rate Limits and Buy credits.

if `docker compose -f backend logs` shows `openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}`, you might be facing the same issue.

**Comment by abi** [comment] 2023-11-22 17:48
Closing this issue since it's filled with different problems and resolutions. Please open a new issue if you run into issues.

**Closed** 2023-11-22 17:48 UTC
