### ISSUE TITLE
Add a prompt for Flutter UI to code

### ISSUE THREAD

**Issue by fisforfaheem** [abi/screenshot-to-code#403] opened 2024-09-10 15:54 UTC
Kindly add a prompt

**Comment by abi** [comment] 2024-09-11 09:45
Yes, planning to. This is a dupe of https://github.com/abi/screenshot-to-code/issues/108

**Closed by abi** 2024-09-11 09:45 UTC

**Comment by fisforfaheem** [comment] 2024-09-20 10:22
sure please! also make it free somehow 👍🏻
